import Head from 'next/head'
import Navbar from '../../components/Navbar'
import { useRouter } from 'next/router';
import { Image } from 'antd';
import styles from '../../styles/faculty.module.css'
import ScrollToTop from "react-scroll-to-top";

// use (router.query.id) to access id from the url

function idPage() {
    const scrollStyle = {
        height: '65px',
        width: '65px',
        borderRadius: '50%',
    }

    const router = useRouter();
    return (
        <>
            <Head>
                <title>NITH CSE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <ScrollToTop smooth='true' width={30} height={30} style={scrollStyle} />

            <section className='facultyDetails'>
                <div className={styles.facultyHeader}>
                    <div className={styles.overlay}></div>
                    <Navbar />
                    <div className={styles.facultyImage}><Image width={400} src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" /></div>
                    <div className={styles.headerText}>
                        <h1>Akshay garg</h1>
                        <p>Full Stack Developer</p>
                    </div>
                </div>
            </section>
        </>
    )
}

export default idPage
