import Loader from '@/components/Loader';
import Head from 'next/head'
import '@/styles/globals.css'
import { useState, useEffect } from 'react';
import { SessionProvider } from "next-auth/react"


export default function App({session, Component, pageProps }) {
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setInterval(() => {
      setLoading(false);
    }, 5000);
  }, [])

  return <>
  <Head>
                <title>NITH CSE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://thumbsnap.com/i/CZmvhUcX.png" />
            </Head>
    {loading ? <Loader /> :
 (
      <SessionProvider session={session}>
        <Component {...pageProps} />
      </SessionProvider>
    )
    }
  </>
}
