import Head from 'next/head'
import Navbar from '../../components/Navbar'
import { Image } from 'antd';
import styles from '../../styles/student_faculty.module.css'
import ScrollToTop from "react-scroll-to-top";
import CustomCursor from 'custom-cursor-react';
import 'custom-cursor-react/dist/index.css';
import { useState, useEffect } from 'react';
import * as FaIcons from "react-icons/fa";
import Jump from 'react-reveal/Jump';
import { EditOutlined } from '@ant-design/icons';
import { Button } from 'antd';
import { signIn, signOut, useSession } from "next-auth/react"
import { useRouter } from 'next/router';
import Link from 'next/link';


function idPage() {
    const [data, setData] = useState([{
        id: 1,
        name: "Akshay garg",
        rollno: "20BCS059",
        skill1: "ReactJS",
        skill2: "NextJS",
        skill3: "ExpressJS",
        semester: "6",
        cgpa: "9.0",
        email: "arnab@nith.ac.in",
        phone: "+91-79-7152 4947",
        github: "https://github.com/akshaygarg034",
        linkedin: "https://www.linkedin.com/in/akshay-garg-360281213/",
        website: "https://google.com",
        img: "https://static.vecteezy.com/system/resources/previews/000/420/940/original/avatar-icon-vector-illustration.jpg",
        address: "Vill- Gulabpura, PO- Panjehra, Teh- Nalagarh, Distt- Solan (HP) - 174101",
        education_10: "Aryan Public Sr. Sec. School Jhiriwala",
        education_12: "Aryan Public Sr. Sec. School Jhiriwala",
        about: "Ph.D, Marketing Strategy & International Business, The University of Texas at Austin , 1992 -1996 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto ipsa earum aspernatur numquam ex alias hic magni exercitationem, unde sit enim facere distinctio eius aperiam molestiae autem eos a ab qui voluptatem!"
    }]);
    const scrollStyle = {
        height: '65px',
        width: '65px',
        borderRadius: '50%',
    }
    const { data: session, status, update } = useSession()
    const router=useRouter();
    const EditFunction =()=>{
        let s="Edit";
if(status==='unauthenticated'){
    s='Sign in'
}
if(status==='authenticated'){
    const {id}=router.query
    if(session.user.email.toLowerCase() === id.toLowerCase())
        return <Button href="/form" type="default" shape="round" icon={<EditOutlined />} size='large' style={{ position: 'absolute', right: '6%', bottom: '2%' }}> {s}</Button>      
}      
    }
    return (
        <>
            <Head>
                <title>NITH CSE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <CustomCursor
                targets={['#home', '#about', '#faculty', '#student', '#moreDetails']}
                customClass='custom-cursor'
                dimensions={100}
                fill='skyblue'
                smoothness={{
                    movement: 0.3,
                    scale: 0.1,
                    opacity: 0.2,
                }}
                opacity={0.5}
                targetOpacity={0.5}
                targetScale={3}
                strokeColor={'#000'}
                strokeWidth={0}
            />
            <ScrollToTop smooth='true' width={30} height={30} style={scrollStyle} />

            <section className='facultyDetails'>
                <div className={styles.studentHeader} style={{ background: "url(/studentbg2.JPG) center center", backgroundSize: "100%", backgroundPositionY: '15%' }}>
                    <div className={styles.overlay} style={{ backgroundColor: 'rgba(0, 0, 0, 0.2)' }}></div>
                    <Navbar />
                    <div className={styles.studentImage}><Image width={400} src={data[0].img} /></div>
                    <div className={styles.headerText}>
                        <h1>{data[0].name}</h1>
                        <p>{data[0].rollno}</p>
                        <Jump>
                            <div className={styles.icons}>
                                <a href={data[0].github} target="_blank" className="fab"><FaIcons.FaGithub />
                                </a>
                                <a href={data[0].linkedin} target="_blank" className="fab"><FaIcons.FaLinkedin />
                                </a>
                            </div>
                        </Jump>
                        <EditFunction/>
                       
                    </div>
                </div>
                <div className={styles.allDetails}>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>About</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <p>{data[0].about}</p>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1 style={{ marginLeft: '-1%' }}>Academic Details</h1>
                            <div style={{ marginLeft: '-46%' }}></div>
                        </div>
                        <div className={styles.data}>
                            <div><p>Semester:</p><span>{data[0].semester}</span></div>
                            <div><p>CGPA:</p><span>{data[0].cgpa}</span></div>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Contact</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <div><p>Email:</p><span>{data[0].email}</span></div>
                            <div><p>Phone:</p><span>{data[0].phone}</span></div>
                            <div><p>Website:</p><a href={data[0].website} style={{ color: "#9e4646" }}>Personal Website</a></div>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Education</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <div><p>10th:</p><span>{data[0].education_10}</span></div>
                            <div><p>12th:</p><span>{data[0].education_12}</span></div>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Address</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <p>{data[0].address}</p>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Skills</h1>
                            <div></div>
                        </div>
                        <div className={`${styles.data} ${styles.skills}`}>
                            <div><p>{data[0].skill1}</p></div>
                            <div><p>{data[0].skill2}</p></div>
                            <div><p>{data[0].skill3}</p></div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default idPage
