import Head from 'next/head'
import Navbar from '../../components/Navbar'
import { useRouter } from 'next/router';
import { Image } from 'antd';
import styles from '../../styles/student_faculty.module.css'
import ScrollToTop from "react-scroll-to-top";

// use (router.query.id) to access id from the url

function idPage() {
    const scrollStyle = {
        height: '65px',
        width: '65px',
        borderRadius: '50%',
    }

    // const router = useRouter();
    return (
        <>
            <Head>
                <title>NITH CSE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <ScrollToTop smooth='true' width={30} height={30} style={scrollStyle} />

            <section className='facultyDetails'>
                <div className={styles.facultyHeader} style={{ background: "url(/facultybg.jpg) center center", backgroundSize: "100%" }}>
                    <div className={styles.overlay}></div>
                    <Navbar />
                    <div className={styles.facultyImage}><Image width={400} src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" /></div>
                    <div className={styles.headerText}>
                        <h1>Shyam Sunder</h1>
                        <p>Full Stack Developer</p>
                    </div>
                </div>
                <div className={styles.allDetails}>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>About</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <p>Ph.D, Marketing Strategy & International Business, The University of Texas at Austin , 1992 -1996 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto ipsa earum aspernatur numquam ex alias hic magni exercitationem, unde sit enim facere distinctio eius aperiam molestiae autem eos a ab qui voluptatem!</p>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Contact</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <div><p>Email:</p><span>arnab@nith.ac.in</span></div>
                            <div><p>Phone:</p><span>+91-79-7152 4947</span></div>
                            <div><p>Secretary:</p><span>Shylaja Deepak</span></div>
                            <div><p>Website:</p><a href='#' style={{ color: "#9e4646" }}>Personal Website</a></div>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Education</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <p>Ph.D, Marketing Strategy & International Business, The University of Texas at Austin , 1992 -1996</p>
                            <p>PGDM, (MBA with concentration in Marketing & Finance), Indian Institute of Management, Ahmedabad, India, 1987-1989</p>
                            <p>Bachelor of Technology , Chemical Engg, Indian Institute of Technology, Kanpur, India, 1982-1986</p>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Address</h1>
                            <div></div>
                        </div>
                        <div className={styles.data}>
                            <p>Vill- Gulabpura, PO- Panjehra, Teh- Nalagarh, Distt- Solan (HP) - 174101 </p>
                        </div>
                    </div>

                    <div className={styles.detail}>
                        <div className={styles.heading}>
                            <h1>Skills</h1>
                            <div></div>
                        </div>
                        <div className={`${styles.data} ${styles.skills}`}>
                            <div><p>HTML</p></div>
                            <div><p>CSS</p></div>
                            <div><p>Javascript</p></div>
                            <div><p>ReactJS</p></div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default idPage
